apiVersion: batch/v1
kind: CronJob
metadata:
  name: dns-updater
  namespace: cron
spec:
  schedule: "*/4 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: dns-updater
            image: curlimages/curl:7.78.0
            args: ["-X", "POST", "https://ispip.tino.sh/$(API_KEY)"]
            env:
              - name: API_KEY
                valueFrom:
                  secretKeyRef:
                    name: dnsupdater
                    key: api-key
          restartPolicy: OnFailure
