apiVersion: v1
kind: Service
metadata:
  labels:
    app: fritzbox-ip-updater-app-service
  name: fritzbox-ip-updater-app-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: fritzbox-ip-updater-backend
